name: Write commit hash to COMMIT_HASH.txt at root

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-commit-hash:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Write short SHA to COMMIT_HASH.txt at root
        run: |
          echo "${{ steps.vars.outputs.sha_short }}" > COMMIT_HASH.txt
          echo "Wrote commit hash ${{ steps.vars.outputs.sha_short }} to COMMIT_HASH.txt"

      - name: Commit and push COMMIT_HASH.txt file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add COMMIT_HASH.txt
          git commit -m "Update COMMIT_HASH.txt with latest commit SHA"
          git push
